% GENERATE CPS DOMAIN SCENARIOS - TWO STEP WORKFLOW
%
% Eight additional CPS domains from real-world datasets, each contributing
% four 2-D uncertainty scenarios. Uncertainty bounds are taken directly from
% the JSON files in data/CPS-extra-domains/ (open datasets / literature).
%
% Domains  (4 scenarios each, IDs 1–36):
%   1–4   Automotive             (KaRaceIng / EV thermal, battery, mechanical)
%   5–8   Building HVAC          (EnergyPlus, ISO 7730)
%   9–12  Industrial Robot       (ISO 10218, welding, assembly)
%   13–16 Medical Device         (IEC 60601, insulin pump, ventilator, …)
%   17–20 Railway                (EN 15227 / SIL, braking, signalling, …)
%   21–24 Satellite Aerospace    (ECSS, attitude control, power, comms)
%   25–28 Smart Grid             (IEEE 1547, ENTSO-E, protection, …)
%   29–32 Water / Chemical       (SWaT dataset, Tennessee-Eastman, …)
%   33–36 Wind Turbine           (FAST / IEC 61400, fatigue, SCADA, …)
%
% Zonotope design (matches Formula Student / CONVIDE convention):
%   Each 2-D scenario pairs two physically related variables from the same
%   domain subsystem.  The source (M1) uses bounds / σ from the JSON directly:
%     interval:      c = (min+max)/2,  g = (max-min)/2
%     probabilistic: c = µ,            g = 1.96·σ  (95 % CI)
%   The target (M2) is derived from the fixed requirement threshold:
%     for "M1 ≤ threshold":  target_c = threshold − 0.25·g,  target_g = 0.25·g
%     for "M1 ≥ threshold":  target_c = threshold + 0.25·g,  target_g = 0.25·g
%   This guarantees a partial but non-trivial intersection for every scenario.
%
% Version: 1.0  —  April 2026

%% Setup
clear; close all; clc;

warning('off', 'CORA:deprecated');
warning('off', 'CORA:contSet:set:expMat');
warning('off', 'CORA:contSet:get:expMat');
warning('off', 'all');
lastwarn('');

%% ═══════════════════════════════════════════════════════════════
%%   CONFIGURATION
%% ═══════════════════════════════════════════════════════════════
run_step1 = true;    % Set false to skip zonotope generation (re-use existing)
run_step2 = true;    % Set false to skip consistency computation

use_saltelli_mode = true;   % true = Saltelli compound interventions
seed = 2025;
rng(seed);

% Consistency scoring (Step 2)
consistency_method   = 'both';
mc_samples           = 1000;
sampling_methods     = {'sobol', 'halton', 'lhs', 'random'};
use_parallel         = true;
n_workers            = 16;

% Scenarios to process (1–36)
scenarios_to_run = 1:36;

%% ═══════════════════════════════════════════════════════════════
%%   PATHS
%% ═══════════════════════════════════════════════════════════════
script_dir   = fileparts(mfilename('fullpath'));
project_root = fileparts(script_dir);
myCORA_dir   = fileparts(project_root);
cps_fw_path  = fullfile(myCORA_dir, 'CPS-Uncertainty-Propagation-Framework');

addpath(fullfile(project_root, 'src', 'matlab'));
addpath(genpath(fullfile(cps_fw_path, 'src')));

addon_path = fullfile(cps_fw_path, 'addons', 'consistency_scoring');
if ~exist(fullfile(addon_path, 'init_consistency_scoring.m'), 'file')
    error('Consistency scoring addon not found at: %s', addon_path);
end
addpath(addon_path);
addpath(fullfile(addon_path, 'methods'));

%% Output directories
data_base    = fullfile(project_root, 'data');
zonotope_dir = fullfile(data_base, 'zonotopes_cps');
results_dir  = fullfile(data_base, 'measurements_cps');

if ~exist(data_base,    'dir'), mkdir(data_base);    end
if ~exist(zonotope_dir, 'dir'), mkdir(zonotope_dir); end
if ~exist(results_dir,  'dir'), mkdir(results_dir);  end

fprintf('===========================================\n');
fprintf('TWO-STEP CPS DOMAIN ANALYSIS\n');
fprintf('===========================================\n');
fprintf('Domains: 9  |  Scenarios per domain: 4  |  Total: 36\n');
fprintf('Zonotopes:    %s\n', zonotope_dir);
fprintf('Results:      %s\n\n', results_dir);

%% ═══════════════════════════════════════════════════════════════
%%   SALTELLI SAMPLES
%% ═══════════════════════════════════════════════════════════════
if use_saltelli_mode
    saltelli_params = {'scale_factor', 'center_delta', 'correlation_strength'};
    saltelli_file   = fullfile(data_base, 'saltelli_samples_3param.csv');
    if ~exist(saltelli_file, 'file')
        % Fall back to formula-student profile if generic is missing
        saltelli_file = fullfile(data_base, 'saltelli_samples_3param_formula_student.csv');
    end
    if ~exist(saltelli_file, 'file')
        error('Saltelli CSV not found. Run generate_saltelli_samples.py first.\nExpected: %s', saltelli_file);
    end
    fprintf('Saltelli samples: %s\n', saltelli_file);
    saltelli_data  = readtable(saltelli_file);
    interventions  = struct('mode', 'saltelli', 'samples', saltelli_data, ...
                            'params', {saltelli_params});
    fprintf('  %d compound interventions loaded.\n\n', height(saltelli_data));
end

%% ═══════════════════════════════════════════════════════════════
%%   PARALLEL POOL
%% ═══════════════════════════════════════════════════════════════
if use_parallel
    delete(gcp('nocreate'));
    pool = gcp('nocreate');
    if isempty(pool)
        parpool('local', n_workers);
    end
end

%% ═══════════════════════════════════════════════════════════════
%%   HELPER: build 2-D conPolyZono
%% ═══════════════════════════════════════════════════════════════
% cpz2d(c1,g1,c2,g2) → conZonotope([c1;c2], diag([g1;g2]), [], [])
cpz2d = @(c1,g1,c2,g2) conZonotope([c1; c2], diag([g1; g2]), [], []);

%% ═══════════════════════════════════════════════════════════════
%%   SCENARIO DEFINITIONS (36 scenarios, 9 domains × 4)
%%
%%   Source M1 : uncertainty taken directly from JSON
%%   Target M2 : derived from fixed requirement threshold:
%%     "≤ thr" → target_c = thr − 0.25·g_src,  target_g = 0.25·g_src
%%     "≥ thr" → target_c = thr + 0.25·g_src,  target_g = 0.25·g_src
%% ═══════════════════════════════════════════════════════════════

all_scenarios = {};

%% ------------------------------------------------------------------
%% DOMAIN 1 – AUTOMOTIVE  (KaRaceIng EV, epistemic + aleatory, IDs 1–4)
%% ------------------------------------------------------------------
%
% Sc 1 – Motor Cooling + Winding Temperature
%   Dim 1: T_motor  [°C]  interval [102,118]  ≤ 110
%   Dim 2: T_wind   [°C]  Gaussian µ=95, σ=4.2  ≤ 105
all_scenarios{end+1} = struct( ...
    'id',   1, ...
    'name', 'Automotive – Motor & Winding Temperature', ...
    'type', 'Thermal', ...
    'source', cpz2d(106.688, 8.0,    101.592, 8.232), ...
    'target', cpz2d(102.0,  8.0,     96.768, 8.232));

% Sc 2 – Battery Capacity + Clutch Engagement
%   Dim 1: E_batt   [kWh]  interval [52.8,64.2]  ≥ 55
%   Dim 2: t_engage [ms]   interval [65,95]       ≤ 85
all_scenarios{end+1} = struct( ...
    'id',   2, ...
    'name', 'Automotive – Battery Capacity & Clutch Delay', ...
    'type', 'Electromechanical', ...
    'source', cpz2d(57.360, 5.7,    78.790, 15.0), ...
    'target', cpz2d(60.700, 5.7,    70.000, 15.0));

% Sc 3 – Suspension Travel + Seat-Belt Force
%   Dim 1: s_susp  [mm]  interval [158,192]   ≤ 180
%   Dim 2: F_belt  [N]   Gaussian µ=2800,σ=320  ≤ 3500
all_scenarios{end+1} = struct( ...
    'id',   3, ...
    'name', 'Automotive – Suspension Travel & Belt Force', ...
    'type', 'Mechanical', ...
    'source', cpz2d(172.962, 17.0,   3240.339, 627.2), ...
    'target', cpz2d(163.0,  17.0,   2872.800, 627.2));

% Sc 4 – Emergency Brake Response + Motor Thermal (probabilistic)
%   Dim 1: t_brake [ms]  interval [125,185]    ≤ 160
%   Dim 2: T_motor [°C]  Gaussian µ=95, σ=4.2  ≤ 105
all_scenarios{end+1} = struct( ...
    'id',   4, ...
    'name', 'Automotive – Brake Response & Thermal Coupling', ...
    'type', 'SafetyCritical', ...
    'source', cpz2d(147.580, 30.0,   101.592, 8.232), ...
    'target', cpz2d(130.000, 30.0,    96.768, 8.232));

%% ------------------------------------------------------------------
%% DOMAIN 2 – BUILDING HVAC  (EnergyPlus / ISO 7730, IDs 5–8)
%% ------------------------------------------------------------------
%
% Sc 5 – Room Temperature + CO2 Concentration
%   Dim 1: T_room   [°C]  interval [19.5,23.5]  ≤ 24
%   Dim 2: C_CO2    [ppm] interval [780,1150]    ≤ 1000
all_scenarios{end+1} = struct( ...
    'id',   5, ...
    'name', 'HVAC – Room Temperature & CO2', ...
    'type', 'Thermal', ...
    'source', cpz2d(23.172, 2.0,    923.410, 185.0), ...
    'target', cpz2d(22.000, 2.0,    815.000, 185.0));

% Sc 6 – Chiller COP + Hydraulic Pressure Drop
%   Dim 1: COP_s   [–]   Gaussian µ=4.2, σ=0.4  ≥ 3.8
%   Dim 2: dP_pipe [Pa]  interval [18500,23000]  ≤ 22000
all_scenarios{end+1} = struct( ...
    'id',   6, ...
    'name', 'HVAC – Chiller COP & Pipe Pressure Drop', ...
    'type', 'Mechanical', ...
    'source', cpz2d(4.1246, 0.784,   21068.500, 2250.0), ...
    'target', cpz2d(4.5840, 0.784,   19750.000, 2250.0));

% Sc 7 – Facade U-Value + Sprinkler Flow
%   Dim 1: U_facade    [W/(m²K)] interval [0.17,0.24]  ≤ 0.2
%   Dim 2: Q_sprinkler [L/min]   interval [78,98]       ≥ 80
all_scenarios{end+1} = struct( ...
    'id',   7, ...
    'name', 'HVAC – Facade U-Value & Sprinkler Flow', ...
    'type', 'Physical', ...
    'source', cpz2d(0.18551, 0.035,   84.140, 10.0), ...
    'target', cpz2d(0.16500, 0.035,   90.000, 10.0));

% Sc 8 – Elevator Bracket Load + BMS Response Time
%   Dim 1: F_bracket [kN]  interval [18.5,26]  ≤ 25
%   Dim 2: t_bms     [s]   interval [8,25]     ≤ 20
all_scenarios{end+1} = struct( ...
    'id',   8, ...
    'name', 'HVAC – Elevator Load & BMS Latency', ...
    'type', 'Cyber', ...
    'source', cpz2d(23.4475, 3.75,   16.481, 8.5), ...
    'target', cpz2d(21.2500, 3.75,   11.500, 8.5));

%% ------------------------------------------------------------------
%% DOMAIN 3 – INDUSTRIAL ROBOT  (ISO 10218 / AWS, IDs 9–12)
%% ------------------------------------------------------------------
%
% Sc 9 – TCP Positioning Error + Wrist Torque
%   Dim 1: err_tcp   [mm]  Gaussian µ=0.08, σ=0.03  ≤ 0.15
%   Dim 2: tau_wrist [Nm]  interval [42,58]          ≤ 55
all_scenarios{end+1} = struct( ...
    'id',   9, ...
    'name', 'Robot – TCP Position Error & Wrist Torque', ...
    'type', 'Mechanical', ...
    'source', cpz2d(0.12566, 0.0588,   51.688, 8.0), ...
    'target', cpz2d(0.09120, 0.0588,   47.000, 8.0));

% Sc 10 – Collaborative Contact Force + Cycle Time
%   Dim 1: F_contact [N]  interval [55,130]    ≤ 110
%   Dim 2: t_cycle   [s]  interval [14.2,17.8] ≤ 16
all_scenarios{end+1} = struct( ...
    'id',   10, ...
    'name', 'Robot – Contact Force & Cycle Time', ...
    'type', 'SafetyCritical', ...
    'source', cpz2d(94.475, 37.5,   15.2548, 1.8), ...
    'target', cpz2d(72.500, 37.5,   14.2000, 1.8));

% Sc 11 – Welding Heat Input + Vision Calibration Error
%   Dim 1: Q_weld   [kJ/mm]  interval [0.48,0.72]           ≤ 0.65
%   Dim 2: err_cal  [mm]     Gaussian µ=0.12, σ=0.04        ≤ 0.20
all_scenarios{end+1} = struct( ...
    'id',   11, ...
    'name', 'Robot – Weld Heat Input & Vision Calibration', ...
    'type', 'Quality', ...
    'source', cpz2d(0.60032, 0.12,   0.16754, 0.0784), ...
    'target', cpz2d(0.53000, 0.12,   0.12160, 0.0784));

% Sc 12 – End-Effector Mass + Controller Bus Jitter
%   Dim 1: m_eff      [kg]  interval [4.8,5.6]  ≤ 5
%   Dim 2: jitter_bus [µs]  interval [2,18]     ≤ 10
all_scenarios{end+1} = struct( ...
    'id',   12, ...
    'name', 'Robot – End-Effector Mass & Bus Jitter', ...
    'type', 'Cyber', ...
    'source', cpz2d(4.8344, 0.4,    6.688, 8.0), ...
    'target', cpz2d(4.6000, 0.4,    2.000, 8.0));

%% ------------------------------------------------------------------
%% DOMAIN 4 – MEDICAL DEVICE  (IEC 60601 / FDA, IDs 13–16)
%% ------------------------------------------------------------------
%
% Sc 13 – Insulin Dose + Ventilator Peak Pressure
%   Dim 1: D_insulin [IU]    interval [4.6,5.4]          ≤ 5.5
%   Dim 2: P_peak    [cmH2O] Gaussian µ=24, σ=3.5        ≤ 30
all_scenarios{end+1} = struct( ...
    'id',   13, ...
    'name', 'Medical – Insulin Dose & Ventilator Pressure', ...
    'type', 'SafetyCritical', ...
    'source', cpz2d(5.3344, 0.4,    27.160, 6.86), ...
    'target', cpz2d(5.1000, 0.4,    23.140, 6.86));

% Sc 14 – Pacemaker Sensing Amplitude + Infusion Line Pressure
%   Dim 1: V_R    [mV]    Gaussian µ=8.5, σ=2.1  ≥ 5.0
%   Dim 2: P_line [mmHg]  interval [280,420]     ≤ 300  (alarm threshold)
all_scenarios{end+1} = struct( ...
    'id',   14, ...
    'name', 'Medical – Pacemaker Sensing & Infusion Pressure', ...
    'type', 'SafetyCritical', ...
    'source', cpz2d(6.7040, 4.116,   271.020, 70.0), ...
    'target', cpz2d(9.1160, 4.116,   230.000, 70.0));

% Sc 15 – Defibrillator Energy + Radiation Tumour Dose
%   Dim 1: E_shock  [J]   interval [145,175]          ≤ 200
%   Dim 2: D_tumour [Gy]  Gaussian µ=59.8, σ=1.5      ≥ 58.0
all_scenarios{end+1} = struct( ...
    'id',   15, ...
    'name', 'Medical – Defibrillator Energy & Radiation Dose', ...
    'type', 'Electrical', ...
    'source', cpz2d(193.790, 15.0,   59.217, 2.94), ...
    'target', cpz2d(185.000, 15.0,   60.940, 2.94));

% Sc 16 – Surgical Robot Tool Force + Drug Plasma Concentration
%   Dim 1: F_tool   [N]     interval [0.8,3.2]         ≤ 3.0
%   Dim 2: C_plasma [ng/mL] Gaussian µ=12.5, σ=2.8     ≤ 18.0
all_scenarios{end+1} = struct( ...
    'id',   16, ...
    'name', 'Medical – Surgical Force & Drug Concentration', ...
    'type', 'Cyber', ...
    'source', cpz2d(2.5032, 1.2,    15.728, 5.488), ...
    'target', cpz2d(1.8000, 1.2,    12.512, 5.488));

%% ------------------------------------------------------------------
%% DOMAIN 5 – RAILWAY  (EN 15227 / SIL, IDs 17–20)
%% ------------------------------------------------------------------
%
% Sc 17 – Braking Distance + Axle Load
%   Dim 1: d_brake [m]  interval [820,1080]  ≤ 1000
%   Dim 2: Q_axle  [kN] interval [148,172]   ≤ 165
all_scenarios{end+1} = struct( ...
    'id',   17, ...
    'name', 'Railway – Braking Distance & Axle Load', ...
    'type', 'SafetyCritical', ...
    'source', cpz2d(946.180, 130.0,   160.032, 12.0), ...
    'target', cpz2d(870.000, 130.0,   153.000, 12.0));

% Sc 18 – Pantograph Contact Force + GNSS Positioning Error
%   Dim 1: F_contact [N]  interval [55,195]          ≤ 180
%   Dim 2: err_gnss  [m]  Gaussian µ=2.8, σ=0.9      ≤ 5.0
all_scenarios{end+1} = struct( ...
    'id',   18, ...
    'name', 'Railway – Pantograph Force & GNSS Error', ...
    'type', 'Electromechanical', ...
    'source', cpz2d(151.020, 70.0,   4.2697, 1.764), ...
    'target', cpz2d(110.000, 70.0,   3.2360, 1.764));

% Sc 19 – Platform Door Gap + Signalling Movement Authority
%   Dim 1: g_door [mm]  interval [45,125]   ≤ 100
%   Dim 2: t_ma   [ms]  interval [280,680]  ≤ 500
all_scenarios{end+1} = struct( ...
    'id',   19, ...
    'name', 'Railway – Door Gap & Signalling Latency', ...
    'type', 'Cyber', ...
    'source', cpz2d(83.440, 40.0,   417.200, 200.0), ...
    'target', cpz2d(60.000, 40.0,   300.000, 200.0));

% Sc 20 – Traction Energy Consumption + Switch Heating Power
%   Dim 1: E_spec  [kWh/km] Gaussian µ=28.5, σ=3.8  ≤ 35
%   Dim 2: P_heat  [W]      interval [1800,2600]     ≤ 2400
all_scenarios{end+1} = struct( ...
    'id',   20, ...
    'name', 'Railway – Traction Energy & Switch Heating', ...
    'type', 'Electrical', ...
    'source', cpz2d(31.9165, 7.448,   2234.400, 400.0), ...
    'target', cpz2d(27.5520, 7.448,   2000.000, 400.0));

%% ------------------------------------------------------------------
%% DOMAIN 6 – SATELLITE AEROSPACE  (ECSS, IDs 21–24)
%% ------------------------------------------------------------------
%
% Sc 21 – Attitude Control Error + Battery Depth of Discharge
%   Dim 1: epsilon_att [arcsec] Gaussian µ=2.8, σ=0.6  ≤ 5.0
%   Dim 2: DoD_max     [%]      interval [28,42]        ≤ 40
all_scenarios{end+1} = struct( ...
    'id',   21, ...
    'name', 'Satellite – Attitude Error & Battery DoD', ...
    'type', 'Cyber', ...
    'source', cpz2d(4.5131, 1.176,   37.102, 7.0), ...
    'target', cpz2d(3.8240, 1.176,   33.000, 7.0));

% Sc 22 – Solar Panel Temperature + Propellant Mass
%   Dim 1: T_panel [°C]  interval [68,92]     ≤ 90
%   Dim 2: m_prop  [kg]  interval [38.2,43.5] ≥ 40.0
all_scenarios{end+1} = struct( ...
    'id',   22, ...
    'name', 'Satellite – Panel Temperature & Propellant Mass', ...
    'type', 'Thermal', ...
    'source', cpz2d(85.032, 12.0,   41.097, 2.65), ...
    'target', cpz2d(78.000, 12.0,   42.650, 2.65));

% Sc 23 – Downlink Data Rate + Reaction Wheel Torque
%   Dim 1: R_downlink [Mbps]  Gaussian µ=28.5, σ=4.2  ≥ 20.0
%   Dim 2: tau_rw     [mNm]   interval [18.0,22.5]    ≥ 20.0
all_scenarios{end+1} = struct( ...
    'id',   23, ...
    'name', 'Satellite – Downlink Rate & Reaction Wheel Torque', ...
    'type', 'Electrical', ...
    'source', cpz2d(23.408, 8.232,   20.932, 2.25), ...
    'target', cpz2d(28.232, 8.232,   22.250, 2.25));

% Sc 24 – Structural Natural Frequency + Onboard RAM Usage
%   Dim 1: f_1      [Hz]  interval [28.5,34.0]  ≥ 30.0
%   Dim 2: RAM_used [MB]  interval [42,58]       ≤ 55
all_scenarios{end+1} = struct( ...
    'id',   24, ...
    'name', 'Satellite – Natural Frequency & RAM Usage', ...
    'type', 'Mechanical', ...
    'source', cpz2d(31.1385, 2.75,   51.688, 8.0), ...
    'target', cpz2d(32.7500, 2.75,   47.000, 8.0));

%% ------------------------------------------------------------------
%% DOMAIN 7 – SMART GRID  (IEEE 1547 / ENTSO-E, IDs 25–28)
%% ------------------------------------------------------------------
%
% Sc 25 – Grid Frequency Nadir + Transformer Loading
%   Dim 1: f_nadir [Hz]  interval [49.2,49.7]          ≥ 49.0
%   Dim 2: S_trafo [kVA] Gaussian µ=380, σ=45           ≤ 400
all_scenarios{end+1} = struct( ...
    'id',   25, ...
    'name', 'SmartGrid – Frequency Nadir & Transformer Load', ...
    'type', 'Electrical', ...
    'source', cpz2d(49.1035, 0.25,    363.485, 88.2), ...
    'target', cpz2d(49.2500, 0.25,    311.800, 88.2));

% Sc 26 – Bus Voltage + Battery Storage SOC
%   Dim 1: V_bus    [pu]  interval [0.98,1.08]  ≤ 1.1
%   Dim 2: SoC_post [%]   interval [18,35]      ≥ 20
all_scenarios{end+1} = struct( ...
    'id',   26, ...
    'name', 'SmartGrid – Bus Voltage & Battery SOC', ...
    'type', 'Electrical', ...
    'source', cpz2d(1.0793, 0.05,   23.519, 8.5), ...
    'target', cpz2d(1.0500, 0.05,   28.500, 8.5));

% Sc 27 – Protection Relay Time + Demand Response Reduction
%   Dim 1: t_relay    [ms]  interval [62,98]           ≤ 80
%   Dim 2: delta_P_dr [MW]  Gaussian µ=42, σ=8         ≥ 35
all_scenarios{end+1} = struct( ...
    'id',   27, ...
    'name', 'SmartGrid – Relay Time & Demand Response', ...
    'type', 'Cyber', ...
    'source', cpz2d(72.548, 18.0,   41.492, 15.68), ...
    'target', cpz2d(62.000, 18.0,   50.680, 15.68));

% Sc 28 – Cable Ampacity + Smart-Meter Latency
%   Dim 1: I_amp  [A]   interval [385,445]  ≥ 400
%   Dim 2: t_ami  [min] interval [5,35]     ≤ 30
all_scenarios{end+1} = struct( ...
    'id',   28, ...
    'name', 'SmartGrid – Cable Ampacity & Meter Latency', ...
    'type', 'Cyber', ...
    'source', cpz2d(412.420, 30.0,   23.790, 15.0), ...
    'target', cpz2d(430.000, 30.0,   15.000, 15.0));

%% ------------------------------------------------------------------
%% DOMAIN 8 – WATER / CHEMICAL PROCESS  (SWaT / TEP, IDs 29–32)
%% ------------------------------------------------------------------
%
% Sc 29 – Tank Level (LIT101) + Inlet Flow (FIT101)
%   Dim 1: LIT101 [mm]    Gaussian µ=525, σ=148   ≤ 1000
%   Dim 2: FIT101 [m³/h]  interval [0.8,1.55]     ≥ 0.5
all_scenarios{end+1} = struct( ...
    'id',   29, ...
    'name', 'Water – Tank Level & Inlet Flow (SWaT)', ...
    'type', 'Physical', ...
    'source', cpz2d(879.907, 290.08,   0.65525, 0.375), ...
    'target', cpz2d(709.920, 290.08,   0.87500, 0.375));

% Sc 30 – UF Pressure Drop + Chlorine Concentration
%   Dim 1: DPIT301 [kPa]  interval [5,35]              ≤ 40
%   Dim 2: AIT202  [mg/L] Gaussian µ=0.52, σ=0.12      ≥ 0.2
all_scenarios{end+1} = struct( ...
    'id',   30, ...
    'name', 'Water – UF Pressure Drop & Chlorine Conc. (SWaT)', ...
    'type', 'Physical', ...
    'source', cpz2d(33.790, 15.0,   0.29737, 0.2352), ...
    'target', cpz2d(25.000, 15.0,   0.43520, 0.2352));

% Sc 31 – Reactor Temperature + Separator Pressure  (Tennessee-Eastman)
%   Dim 1: XMEAS11 [°C]  Gaussian µ=120.4, σ=0.92  ≤ 122.9
%   Dim 2: XMEAS08 [kPa] Gaussian µ=50.1,  σ=0.61  ≤ 52.5
all_scenarios{end+1} = struct( ...
    'id',   31, ...
    'name', 'Chemical – Reactor Temp & Separator Pressure (TEP)', ...
    'type', 'Physical', ...
    'source', cpz2d(122.153, 1.8032,   52.005, 1.1956), ...
    'target', cpz2d(121.097, 1.8032,   51.304, 1.1956));

% Sc 32 – Distillation Column Temperature + Actuator Cylinder Pressure
%   Dim 1: TC_top [°C]  Gaussian µ=78.3, σ=1.8   ≤ 81.5
%   Dim 2: P_cyl  [bar] Gaussian µ=4.1,  σ=0.35  ≤ 6.0
all_scenarios{end+1} = struct( ...
    'id',   32, ...
    'name', 'Chemical – Distillation Temp & Actuator Pressure', ...
    'type', 'Physical', ...
    'source', cpz2d(80.039, 3.528,   5.716, 0.686), ...
    'target', cpz2d(77.972, 3.528,   5.314, 0.686));

%% ------------------------------------------------------------------
%% DOMAIN 9 – WIND TURBINE  (FAST / IEC 61400, IDs 33–36)
%% ------------------------------------------------------------------
%
% Sc 33 – Blade Fatigue Life + Nacelle Vibration
%   Dim 1: N_fatigue [cycles] Gaussian µ=2.5M, σ=180k  ≥ 2.0M
%   Dim 2: a_vib     [mm/s]   interval [2.1,4.8]        ≤ 4.5
all_scenarios{end+1} = struct( ...
    'id',   33, ...
    'name', 'WindTurbine – Blade Fatigue & Nacelle Vibration', ...
    'type', 'Mechanical', ...
    'source', cpz2d(2146059.2, 352800.0,   3.9411, 1.35), ...
    'target', cpz2d(2352800.0, 352800.0,   3.1500, 1.35));

% Sc 34 – Tower Deflection + Power Curve Deviation
%   Dim 1: u_tower [m]  interval [0.42,0.67]           ≤ 0.6
%   Dim 2: delta_P [%]  Gaussian µ=-1.5, σ=2.0         ≥ -5.0
all_scenarios{end+1} = struct( ...
    'id',   34, ...
    'name', 'WindTurbine – Tower Deflection & Power Deviation', ...
    'type', 'Mechanical', ...
    'source', cpz2d(0.54825, 0.125,   -3.3771, 3.92), ...
    'target', cpz2d(0.47500, 0.125,   -1.0800, 3.92));

% Sc 35 – Pitch Actuator Response + Gearbox Oil Temperature
%   Dim 1: t_pitch [s]   interval [3.2,5.8]  ≤ 5.0
%   Dim 2: T_oil   [°C]  interval [62,78]    ≤ 75
all_scenarios{end+1} = struct( ...
    'id',   35, ...
    'name', 'WindTurbine – Pitch Response & Gearbox Oil Temp', ...
    'type', 'Thermal', ...
    'source', cpz2d(4.4618, 1.3,    71.688, 8.0), ...
    'target', cpz2d(3.7000, 1.3,    67.000, 8.0));

% Sc 36 – Foundation Settlement + SCADA Communication Latency
%   Dim 1: theta_settle [mrad]  Gaussian µ=1.8, σ=0.6   ≤ 3.0
%   Dim 2: t_scada      [ms]    interval [45,120]        ≤ 100
all_scenarios{end+1} = struct( ...
    'id',   36, ...
    'name', 'WindTurbine – Foundation Settlement & SCADA Latency', ...
    'type', 'Cyber', ...
    'source', cpz2d(2.5131, 1.176,   84.475, 37.5), ...
    'target', cpz2d(1.8240, 1.176,   62.500, 37.5));

%% ═══════════════════════════════════════════════════════════════
%%   STEP 1: GENERATE ZONOTOPES
%% ═══════════════════════════════════════════════════════════════
if run_step1
    fprintf('\n===========================================\n');
    fprintf('STEP 1: GENERATING ZONOTOPES  (%d scenarios)\n', length(all_scenarios));
    fprintf('===========================================\n');

    gen_options = struct('n_repeats', 1, 'verbose', true, 'use_parallel', use_parallel);

    for k = 1:length(all_scenarios)
        scenario_def = all_scenarios{k};
        if ~ismember(scenario_def.id, scenarios_to_run)
            continue;
        end
        fprintf('\n  [%2d/36] Scenario %d: %s\n', k, scenario_def.id, scenario_def.name);
        try
            causal_experiment_engine_twostep.generate_and_save_zonotopes( ...
                scenario_def, interventions, zonotope_dir, gen_options);
            fprintf('        + done\n');
        catch ME
            fprintf('        x ERROR: %s\n', ME.message);
        end
    end

    fprintf('\n===========================================\n');
    fprintf('STEP 1 COMPLETE → %s\n', zonotope_dir);
    fprintf('===========================================\n');
end

%% ═══════════════════════════════════════════════════════════════
%%   STEP 2: COMPUTE CONSISTENCY SCORES
%% ═══════════════════════════════════════════════════════════════
if run_step2
    fprintf('\n===========================================\n');
    fprintf('STEP 2: COMPUTING CONSISTENCY SCORES\n');
    fprintf('===========================================\n');

    consistency_opts = struct();
    consistency_opts.method          = consistency_method;
    consistency_opts.mc_samples      = mc_samples;
    consistency_opts.sampling_method = sampling_methods;
    consistency_opts.verbose         = false;
    consistency_opts.use_parallel    = use_parallel;

    causal_experiment_engine_twostep.compute_and_save_consistency( ...
        zonotope_dir, results_dir, consistency_opts);

    fprintf('\n===========================================\n');
    fprintf('STEP 2 COMPLETE → %s\n', results_dir);
    fprintf('===========================================\n');
end

%% Summary
fprintf('\n===========================================\n');
fprintf('CPS DOMAIN TWO-STEP WORKFLOW COMPLETE\n');
fprintf('===========================================\n');
fprintf('Zonotopes:    %s\n', zonotope_dir);
fprintf('Measurements: %s\n', results_dir);
fprintf('\nNext: python src/run_analysis.py --data data/measurements_cps\n');
fprintf('===========================================\n\n');
