#!/usr/bin/env python3
"""
run_analysis.py  —  Main entry point for the Python analysis pipeline.

Configure the options below, then run from the project root:
    python src/run_analysis.py

Or override paths via CLI:
    python src/run_analysis.py --data data/measurements --output results

Merge sources first (only needed once):
    python scripts/merge_measurements.py
"""

import sys
import json
import shutil
import tempfile
from pathlib import Path

# ═══════════════════════════════════════════════════════════════
#   CONFIGURE HERE
# ═══════════════════════════════════════════════════════════════

# Where the results_scenario_*.json files live.
# Run scripts/merge_measurements.py once to merge cps + mfmc into data/measurements/.
DATA_DIR = 'data/measurements'

# Root for analysis output (a timestamped sub-directory is created automatically)
OUTPUT_DIR = 'results'

# ── What to run ─────────────────────────────────────────────────
RUN_MFMC               = False    # Apply MFMC correction (adds I_MF_* fields to JSON in-place)
RUN_SENSITIVITY        = True   # Causal effects, local derivatives, Sobol indices,
                                  # robustness margins
RUN_COMPARISON         = True    # Metric comparison ablation: Jaccard vs MC vs MFMC
                                  # (works for both Saltelli and CONVIDE data)
RUN_HEATMAPS           = False    # Inconsistency landscape heatmaps
                                  # (Saltelli mode only — skipped for CONVIDE)
RUN_ANTICAUSAL         = True    # Anticausal inference: P(θ | I(θ)) — which uncertainty
                                  # parameters cause high inconsistency
                                  # (Saltelli mode only)
RUN_LIKELIHOOD_WEIGHTED = False   # Likelihood-weighted inconsistency I_LW = Σ wᵢ·I(θᵢ)
                                  # with fitted TruncatedNormal target
                                  # (Saltelli mode only)
RUN_SURROGATE_FIGURES  = False    # RQ2 figures: GNN accuracy scatter, generalization bar
                                  # chart, runtime comparison
                                  # Requires a trained surrogate in SURROGATE_RESULTS_DIR

# ── Sensitivity options ──────────────────────────────────────────
SOBOL_INDICES    = True   # Compute first-order S_i and total S_T indices (slower)
THRESHOLD        = 0.5    # Inconsistency threshold for robustness-margin computation

# ── Anticausal options ───────────────────────────────────────────
ANTICAUSAL_BINS     = 5                          # Number of bins (used for 'quantile'/'uniform')
ANTICAUSAL_STRATEGY = 'fixed'                    # 'quantile' | 'uniform' | 'fixed'
ANTICAUSAL_EDGES    = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]  # Bin edges for strategy='fixed'

# ── Surrogate paths (only needed when RUN_SURROGATE_FIGURES = True) ─────────
SURROGATE_RESULTS_DIR = 'results/surrogate'   # output dir from train.py
SURROGATE_DATA_ROOT   = 'data/surrogate'      # generated by generate_data.py

# ── Saltelli problem definition ──────────────────────────────────
# Path to the JSON that defines parameter names / bounds for Sobol analysis.
# Set to None to auto-detect (looks for data/saltelli_problem_3param.json).
PROBLEM_FILE = None   # e.g. 'data/saltelli_problem_3param.json'

# ═══════════════════════════════════════════════════════════════
#  ——  DO NOT EDIT BELOW THIS LINE  ——
# ═══════════════════════════════════════════════════════════════

# Ensure the src/analysis/ directory is on the path so all analysis
# modules can be imported directly (invoked as `python src/run_analysis.py`)
sys.path.insert(0, str(Path(__file__).parent / 'analysis'))

from run_full_analysis import run_complete_analysis, detect_experiment_type


# ──────────────────────────────────────────────────────────────────
# Multi-folder merging
# ──────────────────────────────────────────────────────────────────

def _merge_data_dirs(dirs: list[str], tmp_root: Path) -> str:
    """
    Merge scenario JSON files from multiple directories into a single
    temporary directory, resolving filename conflicts by offsetting
    scenario numbers and tagging each file's scenario_name with its
    source folder.

    Offset rule: dir[0] keeps original numbers; dir[k] (k>0) gets
    offset k*1000 added to the scenario number.

    Returns the path to the merged temp directory.
    """
    merged_dir = tmp_root / 'merged'
    merged_dir.mkdir(parents=True, exist_ok=True)

    for dir_idx, data_dir in enumerate(dirs):
        src = Path(data_dir)
        offset = dir_idx * 1000
        label  = src.name  # e.g. 'measurements_cps'

        json_files = sorted(src.glob('results_scenario_*.json'))
        if not json_files:
            print(f'  [merge] WARNING: no results_scenario_*.json found in {src}')
            continue

        print(f'  [merge] {label}: {len(json_files)} file(s)  (scenario offset +{offset})')

        for src_file in json_files:
            # Extract original scenario number from filename
            parts = [p for p in src_file.stem.split('_') if p.isdigit()]
            orig_num = int(parts[-1]) if parts else 0
            new_num  = orig_num + offset

            dst_name = f'results_scenario_{new_num}.json'
            dst_file = merged_dir / dst_name

            # Load, tag, and write
            with open(src_file, encoding='utf-8') as fh:
                data = json.load(fh)

            data['data_source']   = label
            data['scenario_name'] = f'{label}/scenario_{orig_num}'

            with open(dst_file, 'w', encoding='utf-8') as fh:
                json.dump(data, fh, indent=2)

        # Also copy the saltelli_problem file if present (first dir wins)
        for prob_file in src.glob('saltelli_problem*.json'):
            dst = merged_dir / prob_file.name
            if not dst.exists():
                shutil.copy2(prob_file, dst)

    return str(merged_dir)


def _output_name_for_dirs(dirs: list[str]) -> str:
    """Build an output folder name from multiple data dir names."""
    names = [Path(d).name for d in dirs]
    return '_plus_'.join(names)


# ──────────────────────────────────────────────────────────────────
# Individual analysis steps
# ──────────────────────────────────────────────────────────────────

def _run_mfmc(data_dir: str) -> None:
    """Apply MFMC correction via Python (mirrors MATLAB Step 3)."""
    from mfmc_correction import load_scenario_results, process_scenario, augment_json

    data_path  = Path(data_dir).resolve()
    json_files = sorted(data_path.glob('results_scenario_*.json'))
    if not json_files:
        print(f'[MFMC] No files found in {data_dir}')
        return

    print(f'[MFMC] Processing {len(json_files)} scenario file(s)...')
    for jf in json_files:
        data = load_scenario_results(jf)
        parts = [p for p in jf.stem.split('_') if p.isdigit()]
        sid   = int(parts[-1]) if parts else 0
        print(f'  scenario_{sid}', end='  ', flush=True)
        result = process_scenario(data, sid)
        if result is None:
            print('[SKIP]')
            continue
        augmented = augment_json(data, result)
        with open(jf, 'w', encoding='utf-8') as f:
            json.dump(augmented, f, indent=2)
        methods = list(result['methods'].keys())
        parts   = [f"{m}:rho={result['methods'][m]['rho']:+.3f}" for m in methods]
        print(f"[{', '.join(parts)}]")
    print('[MFMC] Done.\n')


def _run_comparison(data_dir: str, output_dir: str) -> None:
    """Metric ablation: Jaccard vs MC (all available methods) vs MFMC.
    Also generates Figure C (runtime table) and Figure D (MC convergence)."""
    from metric_comparison import run_metric_comparison_analysis
    out_dir = Path(output_dir) / 'metric_comparison'
    out_dir.mkdir(parents=True, exist_ok=True)
    run_metric_comparison_analysis(data_dir, str(out_dir))

    # ── Figure C: Runtime vs Accuracy table ───────────────────────────────────
    from generate_runtime_table import (
        _load_experiments as _rt_load, build_table, print_table, save_csv, plot_table,
    )
    rt_dir = Path(output_dir) / 'runtime_table'
    rt_dir.mkdir(parents=True, exist_ok=True)
    rt_exps = _rt_load(data_dir)
    has_timing = any(
        k.startswith('timing_')
        for k in (rt_exps[0].get('pre_state', {}).get('inconsistency', {}) or {}).keys()
    ) if rt_exps else False
    if not has_timing:
        print('[Figure C] WARNING: No timing_* fields — re-run MATLAB after instrumentation.')
    else:
        rows = build_table(rt_exps)
        print_table(rows)
        save_csv(rows, rt_dir / 'runtime_table.csv')
        plot_table(rows, rt_dir / 'figC_runtime_vs_accuracy.pdf')
        plot_table(rows, rt_dir / 'figC_runtime_vs_accuracy.png')
        print(f'[Figure C] Saved to {rt_dir}')

    # ── Figure D: MC convergence vs sample count ──────────────────────────────
    from generate_convergence_figure import (
        _load_experiments as _cv_load, collect_convergence_data,
        print_summary, plot_convergence, plot_convergence_per_method,
    )
    cv_dir = Path(output_dir) / 'convergence'
    cv_dir.mkdir(parents=True, exist_ok=True)
    cv_exps = _cv_load(data_dir)
    cv_data = collect_convergence_data(cv_exps)
    print_summary(cv_data)
    plot_convergence(cv_data, cv_dir / 'figD_convergence_all.pdf')
    plot_convergence(cv_data, cv_dir / 'figD_convergence_all.png')
    plot_convergence_per_method(cv_data, cv_dir)
    print(f'[Figure D] Saved to {cv_dir}')

    # ── Figure E: Pre / Post intervention inconsistency ───────────────────────
    from generate_prepost_figure import (
        load_experiments as _pp_load, build_records as _pp_build,
        plot_prepost,
    )
    pp_dir = Path(output_dir) / 'paper_figures'
    pp_dir.mkdir(parents=True, exist_ok=True)
    pp_exps = _pp_load([data_dir])
    pp_recs = _pp_build(pp_exps)
    if pp_recs:
        plot_prepost(pp_recs, pp_dir / 'figE_prepost_intervention')
        print(f'[Figure E] Saved to {pp_dir}')
    else:
        print('[Figure E] WARNING: No pre/post pairs found.')

    # ── Figure F: Runtime comparison (MC vs MFMC vs Surrogate, log-scale) ──────
    # Requires surrogate timing fields from surrogate experiment runs.
    # Skipped until surrogate experiments are available.
    print('[Figure F] Skipped — requires surrogate runtime data (run surrogate experiments first).')

    # ── Figure G: Estimator Accuracy Comparison ──────────────────────────────
    from generate_metric_comparison_figure import (
        load_experiments as _mc_load, build_records as _mc_build,
        plot_metric_comparison,
    )
    mc_exps = _mc_load([data_dir])
    mc_data = _mc_build(mc_exps)
    if any(len(v) > 0 for v in mc_data.values()):
        plot_metric_comparison(mc_data, pp_dir / 'figG_metric_comparison')
        print(f'[Figure G] Saved to {pp_dir}')
    else:
        print('[Figure G] WARNING: No records with all three metrics found.')

    # ── Figure H: Causal effects / local sensitivity / robustness margins ─────
    from generate_causal_sensitivity_figure import (
        load_data as _cs_load, plot_causal_sensitivity,
    )
    cs_rows = _cs_load([data_dir])
    if cs_rows:
        plot_causal_sensitivity(cs_rows, pp_dir / 'figH_causal_sensitivity')
        print(f'[Figure H] Saved to {pp_dir}')
    else:
        print('[Figure H] WARNING: No compound experiments found.')

    # Figures I-L (surrogate accuracy, generalization, speedup, ranking) are
    # generated separately once surrogate model output is available.


def _run_anticausal(data_dir: str, output_dir: str) -> None:
    """Anticausal inference: P(θ | I(θ)) — which parameters drive inconsistency.
    Also generates Figure A (aggregate Sobol) and Figure B (causal vs anticausal)."""
    from anticausal_inference import load_saltelli_results, run_anticausal_inference

    print(f'[Anticausal] Loading compound experiments from {data_dir}...')
    try:
        df = load_saltelli_results(data_dir)
    except (FileNotFoundError, ValueError) as exc:
        print(f'[Anticausal] SKIP — {exc}')
        return

    out_dir = Path(output_dir) / 'anticausal_inference'
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f'[Anticausal] Running inference ({len(df)} experiments → {out_dir})')
    run_anticausal_inference(
        df,
        k=ANTICAUSAL_BINS,
        strategy=ANTICAUSAL_STRATEGY,
        fixed_edges=ANTICAUSAL_EDGES if ANTICAUSAL_STRATEGY == 'fixed' else None,
        out_dir=str(out_dir),
    )
    print('[Anticausal] Done.\n')

    # ── Figure A: aggregate Sobol ─────────────────────────────────────────────
    from generate_paper_figures import (
        _load_all_sobol,
        plot_aggregate_sobol,
    )
    fig_dir = Path(output_dir) / 'paper_figures'
    fig_dir.mkdir(parents=True, exist_ok=True)
    try:
        sobol_data = _load_all_sobol(Path(output_dir))
        print('[Figure A] Generating aggregate Sobol...')
        plot_aggregate_sobol(sobol_data, fig_dir / 'figA_aggregate_sobol.pdf')
        plot_aggregate_sobol(sobol_data, fig_dir / 'figA_aggregate_sobol.png')
        print(f'[Figure A] Saved to {fig_dir}')
    except FileNotFoundError as exc:
        print(f'[Figure A] SKIP — {exc}')


def _run_surrogate_figures(data_dir: str, output_dir: str) -> None:
    """RQ2 figures: GNN accuracy, generalization, and runtime comparison."""
    import subprocess, sys
    fig_dir = Path(output_dir) / 'paper_figures'
    fig_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable, '-m', 'src.learned_surrogate.generate_rq2_figures',
        '--results_dir', SURROGATE_RESULTS_DIR,
        '--data_root',   SURROGATE_DATA_ROOT,
        '--measurements', data_dir,
        '--output',      str(fig_dir),
    ]
    print(f'[RQ2] Running: {" ".join(cmd)}')
    result = subprocess.run(cmd, cwd=str(Path(__file__).parent.parent))
    if result.returncode != 0:
        print('[RQ2] WARNING: surrogate figure generation failed.')
    else:
        print(f'[RQ2] Figures saved to {fig_dir}')


def _run_likelihood_weighted(data_dir: str, output_dir: str) -> None:
    """Likelihood-weighted inconsistency I_LW = Σ wᵢ·I(θᵢ) with fitted prior."""
    from likelihood_weighted_inconsistency import (
        load_saltelli_dataset,
        TruncatedNormalTarget,
        estimate,
        plot_lw,
    )

    print(f'[LW] Loading compound experiments from {data_dir}...')
    try:
        df = load_saltelli_dataset(data_dir)
    except (FileNotFoundError, ValueError) as exc:
        print(f'[LW] SKIP — {exc}')
        return

    out_dir = Path(output_dir) / 'likelihood_weighted'
    out_dir.mkdir(parents=True, exist_ok=True)

    target  = TruncatedNormalTarget(df)
    results = estimate(df, target)
    plot_lw(results, out_dir=str(out_dir))
    print(f'[LW] Figures saved to {out_dir}')
    print('[LW] Done.\n')


# ──────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description='Python analysis pipeline entry point',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python run_analysis.py
  python run_analysis.py --data data/measurements --output results
  python run_analysis.py --data data/measurements_cps/measurements_cps data/measurements_mfmc
        """,
    )
    default_dirs = [DATA_DIR] if isinstance(DATA_DIR, str) else DATA_DIR
    parser.add_argument(
        '--data',
        nargs='+',
        default=default_dirs,
        metavar='DIR',
        help='One or two data directories containing results_scenario_*.json files',
    )
    parser.add_argument('--output', default=OUTPUT_DIR, help='Output root directory (default: %(default)s)')
    args = parser.parse_args()

    data_dirs  = args.data
    output_dir = str(Path(args.output) / _output_name_for_dirs(data_dirs))

    print('=' * 60)
    print('ANALYSIS PIPELINE')
    for d in data_dirs:
        print(f'  Data:   {d}')
    print(f'  Output: {output_dir}')
    print('=' * 60)

    # ── Merge multiple data dirs if needed ────────────────────────
    _tmp_ctx = None
    if len(data_dirs) > 1:
        print(f'\nMerging {len(data_dirs)} data directories...')
        _tmp_ctx = tempfile.TemporaryDirectory(prefix='cps_analysis_')
        tmp_root = Path(_tmp_ctx.name)
        data_dir = _merge_data_dirs(data_dirs, tmp_root)
        print(f'  Merged into: {data_dir}\n')
    else:
        data_dir = data_dirs[0]

    try:
        # ── MFMC ──────────────────────────────────────────────────────
        if RUN_MFMC:
            print()
            print('=' * 60)
            print('MFMC VARIANCE REDUCTION  (Python)')
            print('=' * 60)
            _run_mfmc(data_dir)

        # ── Sensitivity + heatmaps (via run_full_analysis) ────────────
        if RUN_SENSITIVITY or RUN_HEATMAPS:
            run_complete_analysis(
                data_dir=data_dir,
                output_dir=output_dir,
                analysis_type='sensitivity',
                threshold=THRESHOLD,
                run_sobol=SOBOL_INDICES,
                problem_file=PROBLEM_FILE,
            )

        # ── Metric comparison ablation (independent) ──────────────────
        if RUN_COMPARISON:
            print()
            print('=' * 60)
            print('METRIC COMPARISON  Jaccard / MC / MFMC')
            print('=' * 60)
            _run_comparison(data_dir, output_dir)

        # ── Saltelli-only analyses ─────────────────────────────────────
        exp_type    = detect_experiment_type(data_dir)
        is_saltelli = (exp_type == 'saltelli')

        if RUN_ANTICAUSAL:
            if not is_saltelli:
                print('[Anticausal] SKIP — requires Saltelli / compound-intervention data.')
            else:
                print()
                print('=' * 60)
                print('ANTICAUSAL INFERENCE  P(θ | I(θ))')
                print('=' * 60)
                _run_anticausal(data_dir, output_dir)

        if RUN_LIKELIHOOD_WEIGHTED:
            if not is_saltelli:
                print('[LW] SKIP — requires Saltelli / compound-intervention data.')
            else:
                print()
                print('=' * 60)
                print('LIKELIHOOD-WEIGHTED INCONSISTENCY  I_LW')
                print('=' * 60)
                _run_likelihood_weighted(data_dir, output_dir)

        if RUN_SURROGATE_FIGURES:
            print()
            print('=' * 60)
            print('RQ2 — GNN SURROGATE FIGURES')
            print('=' * 60)
            _run_surrogate_figures(data_dir, output_dir)

    finally:
        if _tmp_ctx is not None:
            _tmp_ctx.cleanup()


if __name__ == '__main__':
    main()
